import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {ClerkProvider} from '@clerk/nextjs'
import React from "react";
import {ToastProvider} from "@/components/providers/toast/toaster-provider";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Lms IPSum',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body className={inter.className}>
                <ToastProvider/>
                {children}
            </body>
            </html>
        </ClerkProvider>
    )
}
